# Generated by Django 4.2.30 on 2026-10-02 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_access_request'),
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackUserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(max_length=40)),
                ('source', models.CharField(default='auto', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_links', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlackNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=80)),
                ('status', models.CharField(default='sent', max_length=10)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_notifications', to='accounts.organization')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_notifications', to='tracker.pullrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlackIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=40)),
                ('team_name', models.CharField(blank=True, max_length=200)),
                ('bot_user_id', models.CharField(blank=True, max_length=40)),
                ('bot_token_encrypted', models.TextField()),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('notify_review_requests', models.BooleanField(default=True)),
                ('send_reminders', models.BooleanField(default=True)),
                ('reminder_after_hours', models.PositiveIntegerField(default=24)),
                ('max_reminders', models.PositiveIntegerField(default=2)),
                ('business_hours_only', models.BooleanField(default=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack', to='accounts.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='slackuserlink',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='uniq_slack_link_per_org_user'),
        ),
        migrations.AddConstraint(
            model_name='slacknotification',
            constraint=models.UniqueConstraint(fields=('kind', 'pull_request', 'user', 'key'), name='uniq_slack_notification'),
        ),
    ]
