# Generated by Django 4.2.30 on 2026-10-02 04:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_delivery_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('action', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'received'), ('processing', 'processing'), ('processed', 'processed'), ('ignored', 'ignored'), ('failed', 'failed')], db_index=True, default='received', max_length=12)),
                ('attempts', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='GitHubInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_installation_id', models.BigIntegerField(unique=True)),
                ('github_account_id', models.BigIntegerField()),
                ('github_account_login', models.CharField(max_length=100)),
                ('account_type', models.CharField(blank=True, max_length=20)),
                ('repository_selection', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installation', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('type', models.CharField(choices=[('repositories', 'Repositories'), ('initial', 'Initial import'), ('incremental', 'Incremental')], max_length=20)),
                ('trigger', models.CharField(default='manual', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('PARTIAL', 'PARTIAL')], db_index=True, default='PENDING', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('reviews_processed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='accounts.organization')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='tracker.repository')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='github_sync_organiz_21aea1_idx')],
            },
        ),
    ]
