# Generated by Django 4.2.30 on 2026-10-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubinstallation',
            name='installed_by_github_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
