# Generated by Django 4.2.30 on 2026-10-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='access_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
