# Generated by Django 4.2.30 on 2026-10-02 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_pr_id', models.BigIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('author_login', models.CharField(db_index=True, max_length=100)),
                ('author_github_id', models.BigIntegerField(blank=True, null=True)),
                ('author_avatar_url', models.URLField(blank=True, max_length=500)),
                ('state', models.CharField(db_index=True, default='open', max_length=10)),
                ('draft', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('review', 'In Review'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('merged', 'Merged'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('base_branch', models.CharField(blank=True, max_length=255)),
                ('head_branch', models.CharField(blank=True, max_length=255)),
                ('merge_commit_sha', models.CharField(blank=True, max_length=64)),
                ('created_at_github', models.DateTimeField(db_index=True)),
                ('updated_at_github', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('merged_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('changed_files', models.IntegerField(default=0)),
                ('commits_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('first_review_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('review_cycles', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at_github'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repository_id', models.BigIntegerField()),
                ('owner', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(db_index=True, max_length=300)),
                ('url', models.URLField(max_length=500)),
                ('default_branch', models.CharField(blank=True, max_length=255)),
                ('private', models.BooleanField(default=False)),
                ('github_created_at', models.DateTimeField(blank=True, null=True)),
                ('github_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_accessible', models.BooleanField(default=True)),
                ('import_status', models.CharField(choices=[('idle', 'Not imported'), ('queued', 'Queued'), ('running', 'Importing'), ('done', 'Imported'), ('failed', 'Failed')], default='idle', max_length=10)),
                ('import_cursor', models.DateTimeField(blank=True, null=True)),
                ('import_total', models.IntegerField(blank=True, null=True)),
                ('import_processed', models.IntegerField(default=0)),
                ('import_error', models.TextField(blank=True)),
                ('import_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('import_started_at', models.DateTimeField(blank=True, null=True)),
                ('import_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'repositories',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PullRequestReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('is_team', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='tracker.pullrequest')),
            ],
            options={
                'ordering': ['assigned_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PullRequestReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_review_id', models.BigIntegerField()),
                ('reviewer', models.CharField(db_index=True, max_length=100)),
                ('reviewer_github_id', models.BigIntegerField(blank=True, null=True)),
                ('reviewer_avatar_url', models.URLField(blank=True, max_length=500)),
                ('state', models.CharField(max_length=30)),
                ('body', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('commit_id', models.CharField(blank=True, max_length=64)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tracker.pullrequest')),
            ],
            options={
                'ordering': ['submitted_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PullRequestLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('color', models.CharField(blank=True, max_length=10)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='tracker.pullrequest')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PullRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('actor', models.CharField(blank=True, max_length=100)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.pullrequest')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='tracker.repository'),
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(fields=('organization', 'github_repository_id'), name='uniq_repo_per_org'),
        ),
        migrations.AddIndex(
            model_name='pullrequestreviewer',
            index=models.Index(fields=['pull_request', 'username'], name='tracker_pul_pull_re_569247_idx'),
        ),
        migrations.AddConstraint(
            model_name='pullrequestreview',
            constraint=models.UniqueConstraint(fields=('pull_request', 'github_review_id'), name='uniq_review_per_pr'),
        ),
        migrations.AddConstraint(
            model_name='pullrequestlabel',
            constraint=models.UniqueConstraint(fields=('pull_request', 'name'), name='uniq_label_per_pr'),
        ),
        migrations.AddConstraint(
            model_name='pullrequestevent',
            constraint=models.UniqueConstraint(fields=('pull_request', 'dedupe_key'), name='uniq_event_per_pr'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['repository', '-created_at_github'], name='tracker_pul_reposit_b09f71_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['status', '-created_at_github'], name='tracker_pul_status_2382ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='pullrequest',
            constraint=models.UniqueConstraint(fields=('repository', 'github_pr_id'), name='uniq_pr_per_repo'),
        ),
        migrations.AddConstraint(
            model_name='pullrequest',
            constraint=models.UniqueConstraint(fields=('repository', 'number'), name='uniq_pr_number_per_repo'),
        ),
    ]
